version: "3.8"
services:

  website:
    image: ghcr.io/envyclient/website
    env_file: .env
    ports:
      - 8080:8000
    volumes:
      - storage:/app/storage
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://127.0.0.1:8000/ping" ]
      retries: 3
      timeout: 5s
    restart: unless-stopped

volumes:
  storage:
