version: "3.8"
services:

  database:
    image: mariadb:10.6.4
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  website:
    image: ghcr.io/envyclient/website
    restart: unless-stopped
    env_file: .env
    command: start:server
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8000"
    volumes:
      - website:/app/storage
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://127.0.0.1:8000/octane-ping" ]
      retries: 3
      timeout: 5s

  worker:
    image: ghcr.io/envyclient/website
    restart: unless-stopped
    env_file: .env
    command: start:worker
    depends_on:
      database:
        condition: service_healthy

volumes:
  database:
  website:
