version: "3.8"
services:

  database:
    image: mariadb:10.6.4
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  cache:
    image: redis:alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  cron:
    image: mcuadros/ofelia
    restart: always
    network_mode: none
    depends_on:
      website:
        condition: service_healthy
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  website:
    image: ghcr.io/envyclient/website
    restart: always
    env_file: .env
    command: start:server
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.pqueue.schedule: "@every 1m"
      ofelia.job-exec.pqueue.command: "php /app/artisan schedule:run"
    ports:
      - "8080:8000"
    volumes:
      - website:/app/storage
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://127.0.0.1:8000/octane-ping" ]
      retries: 3
      timeout: 5s

  horizon:
    image: ghcr.io/envyclient/website
    restart: always
    env_file: .env
    command: start:horizon
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy

volumes:
  database:
  cache:
  website:
