name: Publish Docker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  docker:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: haaaqs/envyclient
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  ssh:
    runs-on: self-hosted
    steps:
      - name: docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/envyclient/
            docker-compose down && docker-compose pull && docker-compose up -d
